server:
  port: ${SERVER_PORT:8085}
  host: ${SERVER_HOST:localhost}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todovehiculos
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Controlador de MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: true
